# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a5404becb9d867bc02787e2b4121cfc06bf1ef36081582ba0dfea8bad795d587fd1bf1b366db5d3e2065e610c1266ba40d7f04dad8af4980462b407038be9454

test:
  secret_key_base: bc276c1fbc4ee50d985ce16dc17e8a230252616b70e639ca4baf9c6c664e6d9d9a112d920a7bfe5a03e53a33c91c7273f5c0419fa153c0befdc2dc9d3ea5b867

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
